# Generated by Django 2.2.10 on 2021-12-10 18:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(choices=[('ludhiana', 'LUDHIANA'), ('chandigarh', 'CHANDIGARH')], default='ludhiana', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('school bag', 'SCHOOL BAG'), ('hand bag', 'HAND BAG'), ('travelling bag', 'TRAVELLING BAG')], default='schoolbag', max_length=20)),
                ('stock', models.CharField(default='10000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_persons', models.PositiveIntegerField(default=0)),
                ('out_persons', models.PositiveIntegerField(default=0)),
                ('total_persons', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('item', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
